SELECT CASE WHEN OCRE.DESCRIPTION LIKE 'PM%'  THEN RIGHT(OCRE.DESCRIPTION,3) ELSE OCRE.DESCRIPTION 
END AS DESCRIPTION,OCRE.ORGANIZATIONNAME,
DEPT.DEPARTMENTNAME AS DEPARTMENT,
RIGHT(DEPT.DEPARTMENTNAME,LENGTH(DEPT.DEPARTMENTNAME)-4) AS DEPARTMENT_NAME,
ITM.ITEMCODE,ITM.ADITMNAME,DTL.CURRENT_STOCK,DTL.UNIT_PRICE,
DTL.COST_PRICE,DTL.MRP,ADITMDEPT,`ITMCGCATEGNAME`,SUBCATEGORY,MANUFACTURER,DTL.BATCH_NO,DTL.EXPIRYDATE,
TAX.TAX,DATE(NOW()) AS 'PREVDATE'
 FROM `STORE_STOCK_DETAIL` DTL
JOIN RT_DATA_DEPARTMENT DEPT
ON DEPT.ID  = DTL.DEPT_ID
JOIN RT_DATA_ITEM  ITM
ON ITM.ID = DTL.ITEM_ID
JOIN RT_DATA_CORE CRE 
ON CRE.ID = DEPT.ID
JOIN RT_ORGANIZATION_CORE OCRE
ON OCRE.ID = CRE.TENANTID
JOIN RT_DATA_TAX TAX ON
TAX.ID =DTL.TAX

JOIN 
`RT_DATA_ITEM_CATEGORY`  CAT ON CAT.ID =ITM.CATEGORY
LEFT JOIN `RT_ORGANIZATION_MANUFACTURER` MANF
ON MANF.ID = ITM.MANUFACTURERID
WHERE (DEPT.DEPARTMENTNAME LIKE '%OPTICALS%'
OR DEPT.DEPARTMENTNAME LIKE '%PHARMACY%'
OR DEPT.DEPARTMENTNAME LIKE '%CONTACT%'
)
AND DTL.CURRENT_STOCK > 0

