SELECT * FROM
(
SELECT 
	IF(ITM.ITEMCODE IS NULL,'',ITM.ITEMCODE) AS 'item_code',
	IF(ITM.ADITMNAME IS NULL,SDTL.ITEMNAME,ITM.ADITMNAME) AS 'item_name',
	SSD.BATCH_NO AS 'batch_no',
	ITM.ADITMUNIT AS 'uom',
	IF(PAT.PATIENTID IS NULL,'Retail Sales',SDTL.SALESDETAILSTATUS) AS 'trans_type',
	DATE(BILL.BILL_DATE) AS 'trans_date',
	IF(ITM.ITEMTYPE = 'F','Frames',IF(ITM.ITEMTYPE = 'L','Lens',IF(ITM.ITEMTYPE = 'M','Material',IF(ITM.ITEMTYPE = 'D','Drugs','Lens')))) AS 'item_type',
	 CASE 
	       	 WHEN ITMC.ITMCGCATEGNAME IN ('FRAMES','LENS','CONTACT LENS','SUNGLASS','OPTICAL LENS') THEN 'OPTICALS' 
	       	 WHEN ITMC.ITMCGCATEGNAME LIKE  ('%OPTICAL SUNGLASS%') THEN 'OPTICALS' 
	       	 WHEN ITMC.ITMCGCATEGNAME LIKE  ('%FRAME%') THEN 'OPTICALS' 
		 WHEN ITMC.ITMCGCATEGNAME IN('PO AND RX SUNGLASS','POST OPERATIVE SG') THEN 'OPTICALS' 
		     WHEN ITMC.ITMCGCATEGNAME LIKE '%PHARMACY%' THEN 'PHARMACY'
		     WHEN ITMC.ITMCGCATEGNAME LIKE '%LAB%' THEN 'LABORATORY'
		       WHEN ITMC.ITMCGCATEGNAME LIKE '%OPERATION THEAT%' THEN 'OPERATION THEATRE'
	
	     END AS 'top',
ITM.ADITMDEPT AS 'second',	

	ITMC.ITMCGCATEGNAME AS 'group',
	ITM.SUBCATEGORY AS 'sub_group',
	BILL.BILL_NO AS 'bill_no',
SALES.SALESNO AS 'sales_no',
	(SDTL.QUANTITY) AS 'quantity',
	IF(SSD.UNIT_PRICE IS NULL , IF(ITM.ADITMUNITRATE IS NULL,ITM.ADITMUNITRATE,ITM.ADITMUNITRATE) ,SSD.UNIT_PRICE) AS 'unit_price',
	IF(SSD.COST_PRICE IS NULL ,IF(ITM.ADITMUNITRATE IS NULL,ITM.ADITMUNITRATE,ITM.ADITMUNITRATE) ,SSD.COST_PRICE) AS 'cost_price',
	(IF(SSD.UNIT_PRICE IS NULL , IF(ITM.ADITMUNITRATE IS NULL,ITM.ADITMUNITRATE,ITM.ADITMUNITRATE) ,SSD.UNIT_PRICE) * (SDTL.QUANTITY)) AS 'actual_value',
	IFNULL(RDT1.TAX,RDT.TAX) AS 'tax',
	IFNULL(RDT1.VALUE,RDT.VALUE) AS 'tax_percent',
	UNIT.ACCOUNTUNIT AS 'branch',
	ROC.DESCRIPTION AS 'entity',
	UNIT.ADDRESSLINE2 AS 'region',
	IF(ITMC.ITMCGCATEGNAME = 'LENS','OPTICAL LENS',DEPT.DEPARTMENTNAME) AS 'unit',
	SALES.WORKORDERSTATUS AS 'wo_status',
	IF(MANF.ID IS NULL,ITM.MANUFACTURERID,MANF.MANUFACTURER) AS MANUFACTURER,
	IFNULL(SSD.MRP,ITM.ADITMMRP) AS MRP
FROM 
	RT_DATA_ACCOUNT_UNIT UNIT 
	JOIN BILL_PATIENT_BILL BILL ON BILL.ACC_UNIT_ID = UNIT.ID
	JOIN RT_DATA_CORE RDC ON RDC.ID=UNIT.ID
	JOIN RT_ORGANIZATION_CORE ROC ON ROC.ID=RDC.TENANTID
	JOIN BILL_SERVICE_DETAIL DTL ON BILL.ID = DTL.BILL_ID
	JOIN RT_TICKET_DIRECTSALES SALES ON DTL.SERVICE_ID = SALES.ID
	JOIN RT_TICKET_DIRECTSALESDETAIL SDTL ON SALES.ID = SDTL.SALESID
	JOIN RT_DATA_ITEM ITM ON ITM.ID = SDTL.ITEMID LEFT JOIN  RT_ORGANIZATION_MANUFACTURER MANF ON MANF.ID = ITM.MANUFACTURERID
	LEFT JOIN RT_DATA_TAX RDT ON RDT.ID=ITM.TAXTYPE
	LEFT JOIN RT_INDIVIDUAL_PATIENT AS PAT ON(BILL.PATIENT_ID = PAT.ID)
	JOIN RT_DATA_ITEM_CATEGORY ITMC ON ITM.CATEGORY = ITMC.ID
	LEFT JOIN STORE_STOCK_DETAIL AS SSD ON (SDTL.STOCKDETAILID = SSD.ID)
	LEFT JOIN RT_DATA_TAX RDT1 ON RDT1.ID=SSD.TAX
	LEFT JOIN RT_DATA_DEPARTMENT AS DEPT ON (SDTL.DEPTID = DEPT.ID)
WHERE 
	DATE(SALES.SALESDATE)=CURDATE()
	AND DTL.SERVICE_ID IS NOT NULL
	AND ROC.DESCRIPTION IN ('AEH','AHC','AHI','AJE')
	AND UNIT.DATASTATUS='Active'
UNION ALL	
SELECT 
	ITM.ITEMCODE AS 'item_code', 
	ITM.ADITMNAME AS 'item-name',
	SSDTL.BATCH_NO,
	ITM.ADITMUNIT AS 'uom',
	SADTL.REASON AS 'trans_type',
	DATE(CRE.CREATEDTIME) AS 'trans_date',
	IF(ITM.ITEMTYPE = 'F','Frames',IF(ITM.ITEMTYPE = 'L','Lens',IF(ITM.ITEMTYPE = 'M','Material',IF(ITM.ITEMTYPE = 'D','Drugs','Lens')))) AS 'item_type',
	CASE 
	       	 WHEN ITMC.ITMCGCATEGNAME IN ('FRAMES','LENS','CONTACT LENS','SUNGLASS','OPTICAL LENS') THEN 'OPTICALS' 
WHEN ITMC.ITMCGCATEGNAME IN('PO AND RX SUNGLASS','POST OPERATIVE SG') THEN 'OPTICALS' 
	       	 WHEN ITMC.ITMCGCATEGNAME LIKE  ('%OPTICAL SUNGLASS%') THEN 'OPTICALS' 
	       	 WHEN ITMC.ITMCGCATEGNAME LIKE  ('%FRAME%') THEN 'OPTICALS' 
		     WHEN ITMC.ITMCGCATEGNAME LIKE '%PHARMACY%' THEN 'PHARMACY'
		     WHEN ITMC.ITMCGCATEGNAME LIKE '%LAB%' THEN 'LABORATORY'
		       WHEN ITMC.ITMCGCATEGNAME LIKE '%OPERATION THEAT%' THEN 'OPERATION THEATRE'
	     END AS 'TOP',
	ITM.ADITMDEPT AS 'second',
	ITM.SUBCATEGORY AS 'group',
	ITM.SUBCATEGORY AS 'sub_group',
	SADTL.ID AS 'bill_no',
	SADTL.ID AS 'Salesno',

	SADTL.QUANTITY AS 'quantity',
	SSDTL.UNIT_PRICE AS 'unit_price',
	SSDTL.COST_PRICE AS 'cost_price',
	IF(SSDTL.COST_PRICE IS NULL ,SSDTL.UNIT_PRICE,SSDTL.COST_PRICE)*SADTL.QUANTITY AS 'actual_value',
	IFNULL(RDT1.TAX,RDT.TAX) AS 'tax',
	IFNULL(RDT1.VALUE,RDT.VALUE) AS 'tax_percent',
	UNIT.ACCOUNTUNIT AS 'branch',
	ROC.DESCRIPTION AS 'entity',
	UNIT.ADDRESSLINE2 AS 'Region',
	DEP.DEPARTMENTNAME AS 'unit',
	'' AS 'wo_status',
	IF(MANF.ID IS NULL,ITM.MANUFACTURERID,MANF.MANUFACTURER) AS MANUFACTURER
	,IFNULL(SSDTL.MRP,ITM.ADITMMRP) 
FROM 
	RT_TICKET_STOCKADJUSTMENTDETAIL SADTL
	JOIN RT_TICKET_CORE CRE ON SADTL.ID = CRE.ID
	JOIN RT_DATA_ITEM ITM ON ITM.ID = SADTL.ITEMID LEFT JOIN  RT_ORGANIZATION_MANUFACTURER MANF ON MANF.ID = ITM.MANUFACTURERID
	JOIN RT_DATA_ITEM_CATEGORY ITMC ON ITM.CATEGORY = ITMC.ID
	LEFT JOIN RT_DATA_TAX RDT ON RDT.ID=ITM.TAXTYPE
	JOIN STORE_STOCK_DETAIL SSDTL ON SADTL.STOCKDETAILID = SSDTL.ID
	LEFT JOIN RT_DATA_TAX RDT1 ON RDT1.ID=SSDTL.TAX
	JOIN RT_DATA_DEPARTMENT DEP ON SADTL.DEPTID = DEP.ID
	JOIN RT_DATA_ACCOUNT_UNIT UNIT ON DEP.ACCOUNTUNITID = UNIT.ID
	JOIN RT_DATA_CORE RDC ON RDC.ID=UNIT.ID
	JOIN RT_ORGANIZATION_CORE ROC ON ROC.ID=RDC.TENANTID
WHERE DATE(CRE.CREATEDTIME)=CURDATE()
	AND TRANSTYPE LIKE 'Reduction'
	AND ROC.DESCRIPTION IN ('AEH','AHC','AHI','AJE')
	AND UNIT.DATASTATUS='Active'
UNION ALL 
SELECT 
	IF(ITM.ITEMCODE IS NULL,'',ITM.ITEMCODE) AS 'item_code',
	IF(ITM.ADITMNAME IS NULL,SDTL.ITEMNAME,ITM.ADITMNAME) AS 'item_name',
	SSD.BATCH_NO,
	ITM.ADITMUNIT AS 'uom',
	IF(PAT.PATIENTID IS NULL,'Retail Sales',SDTL.SALESDETAILSTATUS) AS 'trans_type',
	DATE(RETCORE.CREATEDTIME) AS 'trans_date',
	IF(ITM.ITEMTYPE = 'F','Frames',IF(ITM.ITEMTYPE = 'L','Lens',IF(ITM.ITEMTYPE = 'M','Material',IF(ITM.ITEMTYPE = 'D','Drugs','Lens')))) AS 'item_type',
	 CASE 
	       	 WHEN ITMC.ITMCGCATEGNAME IN ('FRAMES','LENS','CONTACT LENS','SUNGLASS','OPTICAL LENS') THEN 'OPTICALS' 
	       	 WHEN ITMC.ITMCGCATEGNAME LIKE  ('%OPTICAL SUNGLASS%') THEN 'OPTICALS' 
WHEN ITMC.ITMCGCATEGNAME IN('PO AND RX SUNGLASS','POST OPERATIVE SG') THEN 'OPTICALS' 
	       	 WHEN ITMC.ITMCGCATEGNAME LIKE  ('%FRAME%') THEN 'OPTICALS' 
		     WHEN ITMC.ITMCGCATEGNAME LIKE '%PHARMACY%' THEN 'PHARMACY'
		     WHEN ITMC.ITMCGCATEGNAME LIKE '%LAB%' THEN 'LABORATORY'
		       WHEN ITMC.ITMCGCATEGNAME LIKE '%OPERATION THEAT%' THEN 'OPERATION THEATRE'
	     END AS 'TOP',
	ITM.ADITMDEPT AS 'second',	
	ITMC.ITMCGCATEGNAME AS 'group',
	ITM.SUBCATEGORY AS 'sub_group',
	BILL.BILL_NO AS 'bill_no',
	SALES.SALESNO AS 'Salesno',

	-(RETURNDET.RETURNQUANTITY) AS 'quantity',
	IF(SSD.UNIT_PRICE IS NULL , IF(ITM.ADITMUNITRATE IS NULL,ITM.ADITMUNITRATE,ITM.ADITMUNITRATE) ,SSD.UNIT_PRICE) AS 'Unit_price',
	IF(SSD.COST_PRICE IS NULL ,IF(ITM.ADITMUNITRATE IS NULL,ITM.ADITMUNITRATE,ITM.ADITMUNITRATE) ,SSD.COST_PRICE) AS 'cost_price',
	-(IF(SSD.UNIT_PRICE IS NULL , IF(ITM.ADITMUNITRATE IS NULL,ITM.ADITMUNITRATE,ITM.ADITMUNITRATE) ,SSD.UNIT_PRICE) * (RETURNDET.RETURNQUANTITY))  AS 'actual_value',
	IFNULL(RDT1.TAX,RDT.TAX) AS 'tax',
	IFNULL(RDT1.VALUE,RDT.VALUE) AS 'tax_percent',
	UNIT.ACCOUNTUNIT AS 'branch',
	ROC.DESCRIPTION AS 'entity',
	UNIT.ADDRESSLINE2 AS 'Region',
	IF(ITMC.ITMCGCATEGNAME = 'LENS','OPTICAL LENS',DEPT.DEPARTMENTNAME) AS 'unit',
	SALES.WORKORDERSTATUS AS 'wo_status',
	IF(MANF.ID IS NULL,ITM.MANUFACTURERID,MANF.MANUFACTURER) AS MANUFACTURER,
	IFNULL(SSD.MRP,ITM.ADITMMRP) 
FROM 
	RT_DATA_ACCOUNT_UNIT UNIT 
	JOIN BILL_PATIENT_BILL BILL ON BILL.ACC_UNIT_ID = UNIT.ID
	JOIN RT_DATA_CORE RDC ON RDC.ID=UNIT.ID
	JOIN RT_ORGANIZATION_CORE ROC ON ROC.ID=RDC.TENANTID
	JOIN BILL_SERVICE_DETAIL DTL ON BILL.ID = DTL.BILL_ID
	JOIN RT_TICKET_DIRECTSALES SALES ON DTL.SERVICE_ID = SALES.ID
	JOIN RT_TICKET_DIRECTSALESDETAIL SDTL ON SALES.ID = SDTL.SALESID
	JOIN `RT_TICKET_SALESRETURNDETAIL` RETURNDET ON RETURNDET.SALESDETAILID = SDTL.ID
	JOIN RT_TICKET_CORE RETCORE ON RETCORE.ID = RETURNDET.ID
	JOIN RT_DATA_ITEM ITM ON ITM.ID = SDTL.ITEMID LEFT JOIN  RT_ORGANIZATION_MANUFACTURER MANF ON MANF.ID = ITM.MANUFACTURERID
	LEFT JOIN RT_DATA_TAX RDT ON RDT.ID=ITM.TAXTYPE
	LEFT JOIN RT_INDIVIDUAL_PATIENT AS PAT ON(BILL.PATIENT_ID = PAT.ID)
	JOIN RT_DATA_ITEM_CATEGORY ITMC ON ITM.CATEGORY = ITMC.ID
	LEFT JOIN STORE_STOCK_DETAIL AS SSD ON (SDTL.STOCKDETAILID = SSD.ID)
	LEFT JOIN RT_DATA_TAX RDT1 ON RDT1.ID=SSD.TAX
	LEFT JOIN RT_DATA_DEPARTMENT AS DEPT ON (SDTL.DEPTID = DEPT.ID)
WHERE 
	DATE(RETCORE.CREATEDTIME)=CURDATE()
	AND DTL.SERVICE_ID IS NOT NULL
	AND ROC.DESCRIPTION IN ('AEH','AHC','AHI','AJE')
	AND UNIT.DATASTATUS='Active'
	

UNION ALL
SELECT
ITEM.ITEMCODE AS 'item_code',
ITEM.ADITMNAME AS 'item_name',
REGISTER.BATCH_NO AS 'batchNo',
ITEM.ADITMUNIT AS 'uom',
REGISTER.TRANS_TYPE AS 'trans_type',
REGISTER.TRANS_DATE AS 'trans_date',
IF(ITEM.ITEMTYPE = 'F','Frames',IF(ITEM.ITEMTYPE = 'L','Lens',IF(ITEM.ITEMTYPE = 'M','Material',IF(ITEM.ITEMTYPE = 'D','Drugs','Lens')))) AS 'item_type',
CASE
      WHEN CATEGORY.ITMCGCATEGNAME IN ('FRAMES','LENS','CONTACT LENS','SUNGLASS','OPTICAL LENS') THEN 'OPTICALS'

WHEN CATEGORY.ITMCGCATEGNAME IN('PO AND RX SUNGLASS','POST OPERATIVE SG') THEN 'OPTICALS' 
        WHEN CATEGORY.ITMCGCATEGNAME LIKE  ('%OPTICAL SUNGLASS%') THEN 'OPTICALS'
      WHEN CATEGORY.ITMCGCATEGNAME LIKE  ('%FRAME%') THEN 'OPTICALS'
    WHEN CATEGORY.ITMCGCATEGNAME LIKE '%PHARMACY%' THEN 'PHARMACY'
    WHEN CATEGORY.ITMCGCATEGNAME LIKE '%LAB%' THEN 'LABORATORY'
      WHEN CATEGORY.ITMCGCATEGNAME LIKE '%OPERATION THEAT%' THEN 'OPERATION THEATRE'
    END AS 'TOP',
ITEM.ADITMDEPT  AS 'second',
ITEM.SUBCATEGORY AS 'group',
ITEM.SUBCATEGORY AS 'sub_group',
BILL.BILL_NO AS 'bill_no',
'' AS Sales_no,
-REGISTER.TRANS_QTY AS 'quantity',
STOCKDETAIL.UNIT_PRICE AS 'Unit_price',
STOCKDETAIL.COST_PRICE AS 'cost_price',
-(REGISTER.TRANS_QTY*STOCKDETAIL.COST_PRICE) AS 'actual_value',
IFNULL(TAX.TAX,TAX2.TAX) AS 'tax',
IFNULL(TAX.VALUE,TAX2.VALUE) AS 'tax_percent',
UNIT.ACCOUNTUNIT AS 'branch',
ROC.DESCRIPTION AS 'entity',
UNIT.ADDRESSLINE2 AS 'Region',
DEPARTMENT.DEPARTMENTNAME AS 'unit',
'' AS 'wo_status',
MANU.MANUFACTURER AS MANUFACTURER,
STOCKDETAIL.MRP
FROM
STORE_STOCK_REGISTER AS REGISTER
INNER JOIN BILL_PATIENT_BILL AS BILL ON BILL.ID = REGISTER.TRANS_ID
INNER JOIN RT_INDIVIDUAL_PATIENT AS PATIENT ON PATIENT.ID = BILL.PATIENT_ID
INNER JOIN RT_DATA_DEPARTMENT AS DEPARTMENT ON DEPARTMENT.ID = REGISTER.FROM_DEPT_ID
INNER JOIN RT_DATA_ITEM AS ITEM ON ITEM.ID = REGISTER.ITEM_ID
INNER JOIN STORE_STOCK_DETAIL AS STOCKDETAIL ON STOCKDETAIL.ID = REGISTER.ITEM_TRANS_ID
INNER JOIN RT_DATA_ITEM_CATEGORY AS CATEGORY ON ITEM.CATEGORY = CATEGORY.ID
LEFT JOIN RT_DATA_TAX AS TAX ON TAX.ID=STOCKDETAIL.TAX
LEFT JOIN RT_DATA_TAX AS TAX2 ON TAX2.ID=ITEM.TAXTYPE
INNER JOIN RT_DATA_ACCOUNT_UNIT AS UNIT ON DEPARTMENT.ACCOUNTUNITID = UNIT.ID
INNER JOIN RT_DATA_CORE AS RDC ON RDC.ID=UNIT.ID
INNER JOIN RT_ORGANIZATION_CORE AS ROC ON ROC.ID=RDC.TENANTID
LEFT JOIN RT_ORGANIZATION_MANUFACTURER AS MANU ON MANU.ID = ITEM.MANUFACTURERID

WHERE
REGISTER.TRANS_DATE =CURDATE()
AND REGISTER.TRANS_TYPE = 'BILLCANCEL'
AND ROC.DESCRIPTION IN ('AEH','AHC','AHI','AJE')

	
) AS COG
WHERE TOP IS NOT NULL