SELECT entity, NATIVE,SUM(QUANTITY) AS cat_low_end_ct,SUM(NET_AMOUNT) AS cat_low_end_val FROM `revenue_details` 
WHERE -- NATIVE = 'ANN' AND
TRANSACTION_DATE BETWEEN ? AND ?
 AND  UNIT ='SURGERY' AND `GROUP` = 'CATARACT'
AND `SUBGROUP` = 'CATARACT LOW END'
GROUP BY NATIVE;