SELECT entity, NATIVE,SUM(QUANTITY) AS vr_sug_ct,SUM(NET_AMOUNT) AS vr_sug_val FROM `revenue_details` 
WHERE -- NATIVE = 'ANN' AND
TRANSACTION_DATE BETWEEN ? AND ?
AND   UNIT ='SURGERY' AND `GROUP` = 'VITREO RETINAL' AND `SUBGROUP` != 'VR - INJECTION' 
GROUP BY NATIVE;