SELECT entity, NATIVE,SUM(QUANTITY) AS cat_mid_end_ct,SUM(NET_AMOUNT) AS cat_mid_end_val FROM `revenue_details` 
WHERE -- NATIVE = 'ANN' AND
TRANSACTION_DATE BETWEEN ? AND ?
 AND  UNIT ='SURGERY' AND `GROUP` = 'CATARACT'
AND `SUBGROUP` = 'CATARACT MID END'
GROUP BY NATIVE;