SELECT entity, NATIVE,SUM(QUANTITY) AS all_cat_surg_ct,SUM(NET_AMOUNT) AS all_cat_surg_val FROM `revenue_details` 
WHERE -- NATIVE = 'ANN' AND
TRANSACTION_DATE BETWEEN ? AND ?
AND `GROUP` = 'CATARACT'
AND  UNIT ='SURGERY'
GROUP BY NATIVE;