SELECT entity, NATIVE,SUM(QUANTITY) AS cornea_ct,SUM(NET_AMOUNT) AS cornea_val FROM `revenue_details` 
WHERE -- NATIVE = 'ANN' AND
TRANSACTION_DATE BETWEEN ? AND ?
 AND  UNIT ='SURGERY' 
AND  `GROUP` = 'CORNEA'
GROUP BY NATIVE