SELECT entity, NATIVE,SUM(QUANTITY) AS ref_ct,SUM(NET_AMOUNT) AS ref_val FROM `revenue_details` 
WHERE -- NATIVE = 'ANN' AND
TRANSACTION_DATE BETWEEN ? AND ?
AND  `GROUP` = 'REFRACTIVE' AND  UNIT ='SURGERY'
GROUP BY NATIVE;