SELECT entity, NATIVE,SUM(QUANTITY) AS  other_sug_ct,SUM(NET_AMOUNT) AS other_sug_val FROM `revenue_details` 
WHERE -- NATIVE = 'ANN' AND
 TRANSACTION_DATE BETWEEN ? AND ?
AND  `GROUP` NOT IN ('REFRACTIVE','CORNEA','CATARACT') AND  UNIT ='SURGERY'
GROUP BY NATIVE;