SELECT entity, NATIVE,SUM(QUANTITY) AS paid_op_ct FROM `revenue_details` 
WHERE -- NATIVE = 'ANN' AND
TRANSACTION_DATE BETWEEN ? AND ?
AND `GROUP` = 'CONSULTATION'
AND VISIT_TYPE= 'REVIEW'
GROUP BY NATIVE;