SELECT entity, NATIVE,SUM(QUANTITY) AS  treat_ct,SUM(NET_AMOUNT) AS treat_val FROM `revenue_details` 
WHERE -- NATIVE = 'ANN' AND
 TRANSACTION_DATE BETWEEN ? AND ?
AND  UNIT ='TREATMENT'
GROUP BY NATIVE;