SELECT entity, NATIVE,SUM(QUANTITY) AS  invest_ct,SUM(NET_AMOUNT) AS invest_val FROM `revenue_details` 
WHERE -- NATIVE = 'ANN' AND
 TRANSACTION_DATE BETWEEN ? AND ?
AND  UNIT ='INVESTIGATION'
GROUP BY NATIVE;