SELECT entity, NATIVE,COUNT(DISTINCT(billno)) AS optical_ct,SUM(NET_AMOUNT) AS optical_val FROM `revenue_details` 
WHERE -- NATIVE = 'ANN' AND
 TRANSACTION_DATE BETWEEN ? AND ?
AND  UNIT ='OPTICALS'
GROUP BY NATIVE;