SELECT A.BRANCH AS branch,A.VISITDATE AS trans_date,COUNT(*) AS ftd_count

FROM
(
SELECT
IF(BILLACCUNIT.ACCUNITTIMEZONEID=9,IF(PATACCUNIT.ACCUNITTIMEZONEID=9,IF(PATACCUNIT.STATUS != 0,PATACCUNIT.ACCOUNTUNIT,BILLACCUNIT.ACCOUNTUNIT),BILLACCUNIT.ACCOUNTUNIT),BILLACCUNIT.ACCOUNTUNIT)  AS branch
, DATE(BPB.BILL_DATE) AS VISITDATE 

FROM
RT_INDIVIDUAL_PATIENT PAT
LEFT JOIN `RT_DATA_ACCOUNT_UNIT` PATACCUNIT
ON PAT.ACCUNIT = PATACCUNIT.ID
JOIN RT_TICKET_VISIT ON RT_TICKET_VISIT.PATIENTID = PAT.ID
AND STR_TO_DATE(PAT.REGISTEREDDATE,'%d/%m/%Y') < DATE(VISITDATE)
JOIN BILL_PATIENT_BILL BPB ON PAT.ID = BPB.PATIENT_ID  
AND BPB.VISIT_ID = RT_TICKET_VISIT.ID
LEFT JOIN `RT_DATA_ACCOUNT_UNIT` BILLACCUNIT
ON BPB.`ACC_UNIT_ID` = BILLACCUNIT.ID
JOIN BILL_SERVICE_DETAIL BSD ON BSD.BILL_ID = BPB.ID
JOIN RT_DATA_CORE RDC ON RDC.ID = BSD.CHARGEDETAIL_ID
JOIN RT_DATA_CHARGE RDH ON RDH.ID = RDC.PARENT_TICKET_ID
LEFT JOIN `RT_DATA_PAYORTYPE` PAYOR ON PAYOR.ID = BPB.`PAYOR_TYPE_ID`

WHERE
DATE(BPB.BILL_DATE) = DATE_SUB(CURDATE(), INTERVAL 1 DAY)
AND UPPER(RDH.CHARGE) LIKE '%CONSULTA%'
AND BPB.BILL_AMOUNT >0
AND BSD.BILL_STATUS != 2
AND (
(PAYOR.`PAYORCATEGORY`='CASH' AND BPB.DUE_AMOUNT = 0)
OR
(PAYOR.`PAYORCATEGORY` NOT IN ('CASH')
OR
(BPB.`PAYOR_TYPE_ID` IS NULL)
)
)
)AS A
GROUP BY A.BRANCH
, (VISITDATE)

